package oops

import java.lang.IllegalStateException

fun main() {
    val car = Car()
    println(car.type)

    car.maxSpeed = 150
    println(car.maxSpeed)
}


class Car{
    val type = "BMW"
        get() {
            return field.lowercase()
        }

    /**
     * This by default code when creating variable.
     * This code is automatically generated by kotlin in background
     */
//    var maxSpeed: Int = 20
//        get() = field
//        set(value) {
//            field = value
//        }

    /**
     * Custom getter setter
     */
    var maxSpeed: Int = 20
        get() = field
        set(value) {
            field = if(value > 0) value else throw IllegalStateException("Speed cannot be less than 0")
        }
}